-- Quick replies metadata
ALTER TABLE "QuickReply" ADD COLUMN IF NOT EXISTS "createdBy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuickReply" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
