-- Manage Teams: leads + team controls
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "leadIds" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "teamShowMembersInAssignee" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "teamLeadCanAssignContacts" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "teamLeadCanViewTeamContacts" BOOLEAN NOT NULL DEFAULT true;
